---
                                                                                                    title: "Akram_Backprop"
output: html_document
---

Import packages:

```{r}

library(ggplot2)
library(tidyr)
library(dplyr)
library(patchwork)
library(lubridate)
library(zoo)
library(Hmisc)
library(ggcorrplot)
library(corrplot)
library(ggpubr)
library(caret)
library(car)
library(glmnet)
library(modelr)
library(broom)
library(neuralnet)
library(NeuralNetTools)
library(Metrics)

path = "~/Desktop/NYCDSA/Homework/Project3/Akram/3 - Backprop Models"
setwd(path)

```

Import dataframe:

```{r}

df_backprop = read.csv("~/Desktop/NYCDSA/Homework/Project3/Akram/2 - Regression Models/df_Backprop_Engineered.csv", stringsAsFactors = TRUE)

df_backprop_engineered = select(df_backprop, -c(X, PID, Neighborhood, RoofStyle, Exterior1st, MSZoning, Foundation, Heating, GarageFinish, SaleCondition, HouseStyle, BsmtFullBath, FullBath, BldgType, GarageType, Exterior2nd))

head(df_backprop_engineered)

```

Max-Min normalisation function:

```{r}

# Max-Min Normalisation

normalize = function(x) {
 return ((x - min(x)) / (max(x) - min(x)))
}

```


Creation of training and test set data:

```{r}

# We split the data into a training and test set

set.seed(500)

training.samples = sample(nrow(df_backprop_engineered), 0.7*nrow(df_backprop_engineered))

maxmindf = as.data.frame(lapply(df_backprop_engineered, normalize))

train.data = maxmindf[training.samples, ]

test.data = maxmindf[-training.samples, ]

```
 

Neural Network - Backpropagation (36,2) layer

```{r}

# Implementation of Neural Network

ames_backprop = neuralnet(logSalePrice ~
                    GrLivArea + #LotArea +
                    Neighborhood_Int + 
                      Age +
                    StreetAlley + 
                    MSZoning_Int +
                      #RemodSinceBuilt +
                    #LotShape + 
                      #LandContour +
                    #LandSlope + 
                      #LotConfig +
                    IsOnMainroad + 
                      #IsNearPark +
                    IsNearRailroad +
                      #BsmtQual +
                    OverallQual + 
                      OverallCond +
                    ExterQual + 
                      BsmtExposure + 
                      #Rate +
                    TotalBsmtSF +  
                      KitchenQual + 
                    #Fireplaces + 
                      GarageQual + 
                    #GarageCond + 
                      #GarageCars +                      
                    #KitchenAbvGr + 
                      #PavedDrive + 
                    #EnclosedPorch + 
                      #ScreenPorch + 
                    AllBathrooms + 
                      CentralAir +
                      #FireplaceQu + 
                    #Functional + 
                      #TotRmsAbvGrd + 
                    BedroomAbvGr + 
                      HeatingQC,
                  data = train.data, likelihood = TRUE, 
                  hidden=c(11,6), linear.output=TRUE, threshold=0.005)

# Neural network results

ames_backprop$result.matrix

plot(ames_backprop, file="Backprop_Diagram")

ames_backprop$net.result

# Test the resulting output with test.data

testset = select(test.data, -logSalePrice)

nn.results_test = compute(ames_backprop, testset)

results_test = data.frame(actual = test.data$logSalePrice, prediction = nn.results_test$net.result)

results_test

# Test the resulting output with train.data for R2_Train

trainset = select(train.data, -logSalePrice)

nn.results_train = compute(ames_backprop, trainset)

results_train = data.frame(actual = train.data$logSalePrice, prediction = nn.results_train$net.result)

results_train

```




```{r}

R2_general = function(actual, predictions){
                rsquared = 1 - sum((predictions - actual)^2)/sum((actual - mean(actual))^2)
                return(rsquared)
              }

R2_Backprop_Train = R2_general(results_train$actual, results_train$prediction)

R2_Backprop_Test = R2_general(results_test$actual, results_test$prediction)

RMSE_Backprop_Test = rmse(results_test$actual, results_test$prediction)

AIC_Backprop = as.double(ames_backprop$result.matrix["aic",1])

BIC_Backprop = as.double(ames_backprop$result.matrix["bic",1])

```



```{r}

sink("Backpropagation_Results.txt")
cat(paste("Ames Backpropagation Neural Network Results:"),
    paste("R^2 Train = ", R2_Backprop_Train),
    paste("R^2 Test = ", R2_Backprop_Test),
    paste("RMSE Test = ", RMSE_Backprop_Test),
    paste("AIC = ", AIC_Backprop),
    paste("BIC = ", BIC_Backprop), sep="\n")
sink()

cat(paste("Ames Backpropagation Neural Network Results:"),
    paste("R^2 Train = ", R2_Backprop_Train),
    paste("R^2 Test = ", R2_Backprop_Test),
    paste("RMSE Test = ", RMSE_Backprop_Test),
    paste("AIC = ", AIC_Backprop),
    paste("BIC = ", BIC_Backprop), sep="\n")

```
